// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ykogauihftqfengpagha.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlrb2dhdWloZnRxZmVuZ3BhZ2hhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NzUyNjUsImV4cCI6MjA3MDE1MTI2NX0.IcuJhWQx04ppwrH8g9fHh9lrg2C1shGmuLmuFXSjNRs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});